# entityName: ProcessGroup
# entityNamePlural: ProcessGroups
# idType: Long
# packageName: com.asl.core
# subPackageName:
# moduleName: process

# fields:
#   - name: name
#     type: String
#     constraints: ["NotBlank"]
#   - name: description
#     type: String
#     constraints: []
entityName: ProcessType
entityNamePlural: ProcessTypes
idType: Long
packageName: com.asl.core
subPackageName:
moduleName: process

fields:
  - name: name
    type: String
    constraints: ["NotBlank"]
  - name: description
    type: String
    constraints: []
  - name: duration
    type: Integer
    constraints: ["NotNull", "Min(0)"]
  - name: status
    type: String
    constraints: ["NotBlank"]
  - name: cost
    type: Double
    constraints: ["NotNull", "Min(0)"]
